version: "3.4"

services:
  postgresql_desafio_back_end:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=movies
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin

  back_end:
    container_name: desafio_back_end
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_desafio_back_end
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/movies
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  database-data:
  pgadmin: